export const DECISION_RULE_TOKEN = Symbol('DECISION_RULE_TOKEN');

export const RULE_PRIORITIES = {
  INFRASTRUCTURE: 10,
  TRIVIAL_FILTERS: 20,
  BUSINESS_CONSTRAINTS: 30,
  DETERMINISTIC_RULES: 40,
  SEMANTIC_CACHE: 50,
} as const;
